# Generated by Django 5.2.3 on 2025-06-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='mostrar_portfolio',
            field=models.BooleanField(default=True, help_text='Exibir item Portfólio no menu'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='mostrar_servicos',
            field=models.BooleanField(default=True, help_text='Exibir item Serviços no menu'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='mostrar_sobre',
            field=models.BooleanField(default=True, help_text='Exibir item Sobre no menu'),
        ),
    ]
